name: Packer Consul AWS

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
    types: [opened, synchronize]

jobs:
  Validate-Packer:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Validate-Packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Template
        uses: jveraduran/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/packer.json.pkr.hcl
  
  Format-Packer:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Format-Packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Template
        uses: jveraduran/packer-github-actions@master
        with:
          command: fmt
          target: packer/packer.json.pkr.hcl

  # Build:
  #   needs: [Validate-Packer,Format-Packer]
  #   if: ${{ (github.event_name == 'push') && always() }}
  #   runs-on: ubuntu-latest
  #   name: Build
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
      
  #     - name: Setup ENV
  #       shell: bash
  #       run: |-
  #         if [ ${{ github.event_name }} == "pull_request" ]; then 
  #           branch=$(echo ${{ github.base_ref }}  | tr / -)
  #         else 
  #           branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
  #         fi
  #         if [ $branch = "master" ]; then 
  #           env="production";
  #         elif [ $branch = "develop" ]; then 
  #           env="develop";
  #         elif [ $branch = "staging" ]; then 
  #           env="staging";
  #         else 
  #           echo "invalid environment"; exit -1
  #         fi
  #         echo "ENV=$(echo $env)" >> $GITHUB_ENV
      
  #     - name: Download Packer Plugin
  #       uses: jveraduran/packer-github-actions@master
  #       with:
  #         command: init
  #         target: aws/packer-consul.json.pkr.hcl

  #     - name: Build Artifact
  #       uses: jveraduran/packer-github-actions@master
  #       with:
  #         command: build
  #         arguments: "-color=false -on-error=abort -force -var version=${{ github.run_number }}"
  #         target: aws/packer-consul.json.pkr.hcl
  #       env:
  #         AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  #         AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  #         AWS_REGION: "us-east-1"
  #         CONSUL_HTTP_ADDR: ${{ secrets.CONSUL_HTTP_ADDR }}
  #         CONSUL_HTTP_TOKEN: ${{ secrets.CONSUL_HTTP_TOKEN }}
  #         APP_ENV: ${{ env.ENV }}
  #         HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  #         HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

        